### ISSUE TITLE
发现问题

### ISSUE THREAD

**Issue by brucewuu520** [pedant/safe-java-js-webview-bridge#4]
发现一问题，JsCallback回调时报空指针错误：
Caused by: java.lang.NullPointerException
    at android.webkit.WebViewClassic.loadUrlImpl(WebViewClassic.java:2678)
    at android.webkit.WebViewClassic.loadUrlImpl(WebViewClassic.java:2694)
    at android.webkit.WebViewClassic.loadUrl(WebViewClassic.java:2687)
    at android.webkit.WebView.loadUrl(WebView.java:804)
    at cn.pedant.SafeWebViewBridge.JsCallback.apply(JsCallback.java:42)
    at com.jidian.android.edo.util.HostJsScope$2.onComplete(HostJsScope.java:137)

我猜测可能是这样的，因为回调有延迟，callback.apply()的时候可能webview已经被关闭，导致的这个错误

**Comment by guofeng007** [comment]
看下出现这个crash的手机系统是不是4.1.2,这个版本上的webview的问题，参见下面的链接
https://groups.google.com/forum/#!topic/google-admob-ads-sdk/tjqDzFJk98w

sorry这个可能不准，在其他地方也看到这个类似的bug，
